Repository dead-space-server/space-station-14-resources, pull requests merged in 2024-12, with the labels that each got.

#73 Лодауты ОБР
  Resources/Locale/en-US/thief/backpack.ftl
  Resources/Locale/ru-RU/deadspace/prototypes/entities/ertloadouts.ftl
  Resources/Locale/ru-RU/thief/backpack.ftl
  Resources/Prototypes/Catalog/thief_toolbox_sets.yml
  Resources/Prototypes/DeadSpace/Entities/Other/ertloadouts.yml
  Resources/Prototypes/DeadSpace/Roles/Jobs/CentComm/cburn.yml
  Resources/Prototypes/DeadSpace/Roles/Jobs/CentComm/deathsquad.yml
  Resources/Prototypes/DeadSpace/Roles/Jobs/CentComm/emergencyresponseteam.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Roles/Jobs/CentComm/deathsquad.yml
  Resources/Textures/DeadSpace/Other/ertloadouts/ertboxes.rsi/amber.png
  Resources/Textures/DeadSpace/Other/ertloadouts/ertboxes.rsi/cburn.png
  Resources/Textures/DeadSpace/Other/ertloadouts/ertboxes.rsi/gamma.png
  Resources/Textures/DeadSpace/Other/ertloadouts/ertboxes.rsi/meta.json
  Resources/Textures/DeadSpace/Other/ertloadouts/ertboxes.rsi/red.png
  Resources/Textures/DeadSpace/Other/ertloadouts/ertcases.rsi/amber.png
  Resources/Textures/DeadSpace/Other/ertloadouts/ertcases.rsi/cburn.png
  Resources/Textures/DeadSpace/Other/ertloadouts/ertcases.rsi/gamma.png
  Resources/Textures/DeadSpace/Other/ertloadouts/ertcases.rsi/meta.json
  Resources/Textures/DeadSpace/Other/ertloadouts/ertcases.rsi/red.png
  Resources/Textures/Interface/Misc/job_icons.rsi/Coroner.png
Labels: Status: Needs Review

#79 🔄 synced file(s) with dead-space-server/space-station-14
  Resources/Locale/ru-RU/job/job-description.ftl
  Resources/Prototypes/DeadSpace/Roles/Jobs/Law/magistrate.yml
Labels: Sync

#99 Респрайт респрайта КПК и айди карт
  Resources/Textures/Objects/Devices/pda.rsi/pda-brigmedic.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-chemistry.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-cmo.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-cook.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-coroner.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-genetics.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-hos.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-interncadet.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-medical.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-mime.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-paramedic.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-rd.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-science.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-security.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-seniorofficer.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-seniorphysician.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-seniorresearcher.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-surgeon.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-syndi-agent.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-virology.png
  Resources/Textures/Objects/Devices/pda.rsi/pda-warden.png
  Resources/Textures/Objects/Misc/id_cards.rsi/idbrigmedic.png
  Resources/Textures/Objects/Misc/id_cards.rsi/iddetective.png
  Resources/Textures/Objects/Misc/id_cards.rsi/idheadofsecurity.png
  Resources/Textures/Objects/Misc/id_cards.rsi/idintern-cadet.png
  Resources/Textures/Objects/Misc/id_cards.rsi/idsecurityofficer.png
  Resources/Textures/Objects/Misc/id_cards.rsi/idsecuritypilot.png
  Resources/Textures/Objects/Misc/id_cards.rsi/idseniorofficer.png
  Resources/Textures/Objects/Misc/id_cards.rsi/idwarden.png
Labels: Status: Awaiting Changes
