Repository dead-space-server/space-station-14-resources, pull requests merged in 2024-11, with the labels that each got.

#40 🔄 synced file(s) with dead-space-server/space-station-14
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
  Resources/Prototypes/Corvax/tts-voices.yml
  Resources/Prototypes/DeadSpace/Entities/Objects/Specific/Janitorial/soap.yml
  Resources/Prototypes/DeadSpace/Necromorfs/leviathan.yml
  Resources/Prototypes/DeadSpace/Necromorfs/necromorfs.yml
  Resources/Prototypes/DeadSpace/Roles/Jobs/CentComm/specialoperationsofficer.yml
  Resources/Prototypes/DeadSpace/Spiders/spiders.yml
  Resources/Prototypes/DeadSpace/Sponsor/drippenwagenAlt.yml
Labels: Sync

#45 🔄 synced file(s) with dead-space-server/space-station-14
  Resources/Prototypes/DeadSpace/Necromorfs/gamerules.yml
  Resources/Prototypes/DeadSpace/Necromorfs/leviathan.yml
  Resources/Prototypes/DeadSpace/Necromorfs/uplink.yml
Labels: Sync

#49 Доминатор fgfgfgh
  Resources/Prototypes/DeadSpace/Sponsor/fffgfgggg.yml
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/backpack.rsi/equipped-BACKPACK.gif
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/backpack.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/backpack.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/gas.rsi/equipped-MASK.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/gas.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/gas.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/gas.rsi/inhand-right.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/gas.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/gloves.rsi/equipped-HAND.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/gloves.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/gloves.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/gloves.rsi/inhand-right.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/gloves.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/hardsuit.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/hardsuit.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/hardsuit.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/hardsuit.rsi/inhand-right.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/hardsuit.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/helmet.rsi/icon-flash.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/helmet.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/helmet.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/helmet.rsi/off-equipped-HELMET.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/helmet.rsi/on-equipped-HELMET.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/hud.rsi/equipped-EYES.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/hud.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/hud.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/hud.rsi/inhand-right.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/hud.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/jumpsuit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/jumpsuit.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/jumpsuit.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/jumpsuit.rsi/inhand-right.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/jumpsuit.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/magboots.rsi/equipped-FEET.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/magboots.rsi/icon-on.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/magboots.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/magboots.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/magboots.rsi/inhand-right.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/magboots.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/magboots.rsi/on-equipped-FEET.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/magboots.rsi/on-inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/magboots.rsi/on-inhand-right.png
  Resources/Textures/DeadSpace/Sponsor/fffgfgggg/mantle.rsi/equipped(poka 2 storony) .png
Labels: Status: Needs Review

#52 Разные фиксы
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
  Resources/Prototypes/DeadSpace/Entities/Objects/Devices/typan_pda.yml
  Resources/Textures/Clothing/Belt/holster.rsi/equipped-NECK.png
  Resources/Textures/Clothing/Belt/holster.rsi/meta.json
  Resources/Textures/Clothing/Belt/syndieholster.rsi/equipped-NECK.png
  Resources/Textures/Clothing/Belt/syndieholster.rsi/meta.json
  Resources/Textures/DeadSpace/Clothing/Head/Hats/beret_blueshield.rsi/meta.json
  Resources/Textures/DeadSpace/Necromorfs/dead_squad.rsi/running.png
  Resources/Textures/DeadSpace/Spiders/cburn/cburnxeno.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Spiders/cburn/cburnxeno.rsi/inhand-right.png
Labels: Status: Approved

#54 🔄 synced file(s) with dead-space-server/space-station-14
  Resources/Locale/ru-RU/actions/actions/sleep.ftl
  Resources/Locale/ru-RU/damage/damage-force-say.ftl
  Resources/Locale/ru-RU/deadspace/photocopier/paperwork.ftl
  Resources/Locale/ru-RU/game-ticking/game-presets/preset-sandbox.ftl
  Resources/Paperwork/Law/11.xml
  Resources/Paperwork/Law/6.xml
  Resources/Prototypes/DeadSpace/Entities/Paperwork/law.yml
Labels: Sync

#56 🔄 synced file(s) with dead-space-server/space-station-14
  Resources/Prototypes/DeadSpace/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/DeadSpace/lobbyscreens.yml
  Resources/Prototypes/Entities/Objects/Decoration/present.yml
  Resources/Prototypes/Maps/aspid.yml
  Resources/Textures/DeadSpace/Items/Toys/toys.rsi/meta.json
  Resources/Textures/DeadSpace/Items/Toys/toys.rsi/plushie_cap.png
  Resources/Textures/DeadSpace/Items/Toys/toys.rsi/plushie_hos.png
  Resources/Textures/DeadSpace/Items/Toys/toys.rsi/plushie_instructor.png
  Resources/Textures/DeadSpace/Items/Toys/toys.rsi/plushie_kel.png
  Resources/Textures/DeadSpace/Items/Toys/toys.rsi/plushie_lera.png
  Resources/Textures/DeadSpace/Items/Toys/toys.rsi/plushie_officer.png
  Resources/Textures/LobbyScreens/Fobos/attributions.yml
  Resources/migration.yml
Labels: Sync
