Repository dead-space-server/space-station-14-resources, pull requests merged in 2024-10, with the labels that each got.

#10 Доминатор DragonFoxVRC
  Resources/Prototypes/DeadSpace/Sponsor/dragon_fox.yml
  Resources/Textures/DeadSpace/Sponsor/DragonFox/belt.rsi/equipped-BELT.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/belt.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/belt.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/belt.rsi/inhand-right.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/belt.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/DragonFox/gas.rsi/gas-equipped.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/gas.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/gas.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/gas.rsi/inhand-right.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/gas.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/DragonFox/helmet_suit.rsi/icon-on.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/helmet_suit.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/helmet_suit.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/DragonFox/helmet_suit.rsi/off-equipped-HELMET.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/helmet_suit.rsi/on-equipped-HELMET.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/hud.rsi/equipped-EYES.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/hud.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/hud.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/hud.rsi/inhand-right.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/hud.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/DragonFox/jumpsuit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/jumpsuit.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/jumpsuit.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/jumpsuit.rsi/inhand-right.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/jumpsuit.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/DragonFox/suit.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/suit.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/suit.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/DragonFox/suit.rsi/suit-inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/suit.rsi/suit-inhand-right.png
Labels: Status: Approved

#18 🔄 synced file(s) with dead-space-server/space-station-14
  Resources/Locale/ru-RU/deadspace/sponsor/dragon_fox.ftl
  Resources/Prototypes/DeadSpace/Entities/Objects/Weapons/Melee/chainsword.yml
  Resources/Prototypes/DeadSpace/Sponsor/dragon_fox.yml
  Resources/Textures/DeadSpace/Sponsor/DragonFox/helmet_suit.rsi/icon-flash.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/helmet_suit.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/DragonFox/suit.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/suit.rsi/inhand-right.png
Labels: Sync

#19 Скафандр боевых сестёр по запросу Доминатора
  Resources/Prototypes/DeadSpace/Sponsor/dragon_fox.yml
  Resources/Textures/DeadSpace/Sponsor/DragonFox/SisterOfBattle/hardsuit.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/SisterOfBattle/hardsuit.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/SisterOfBattle/hardsuit.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/SisterOfBattle/hardsuit.rsi/inhand-right.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/SisterOfBattle/hardsuit.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/DragonFox/SisterOfBattle/head.rsi/icon-flash.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/SisterOfBattle/head.rsi/icon.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/SisterOfBattle/head.rsi/meta.json
  Resources/Textures/DeadSpace/Sponsor/DragonFox/SisterOfBattle/head.rsi/off-equipped-HELMET.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/SisterOfBattle/head.rsi/on-equipped-HELMET.png
Labels: Status: Needs Review

#23 Фикс доминатор Dragon_fox
  Resources/Prototypes/DeadSpace/Sponsor/dragon_fox.yml
  Resources/Textures/DeadSpace/Sponsor/DragonFox/gas.rsi/equipped-MASK.png
  Resources/Textures/DeadSpace/Sponsor/DragonFox/gas.rsi/meta.json
Labels: Status: Needs Review

#15 Изменение правил сервера на актуальные
  Resources/Prototypes/DeadSpace/Guidebook/rules.yml
  Resources/ServerInfo/DeadSpace/Guidebook/ServerRules/DeadSpaceDefaultRule3.xml
  Resources/ServerInfo/DeadSpace/Guidebook/ServerRules/DeadSpaceDefaultRule31.xml
  Resources/ServerInfo/DeadSpace/Guidebook/ServerRules/DeadSpaceDefaultRule32.xml
  Resources/ServerInfo/DeadSpace/Guidebook/ServerRules/DeadSpaceDefaultRule33.xml
  Resources/ServerInfo/DeadSpace/Guidebook/ServerRules/DeadSpaceDefaultRule34.xml
  Resources/ServerInfo/DeadSpace/Guidebook/ServerRules/DeadSpaceDefaultRule35.xml
  Resources/ServerInfo/DeadSpace/Guidebook/ServerRules/DeadSpaceDefaultRule36.xml
  Resources/ServerInfo/DeadSpace/Guidebook/ServerRules/DeadSpaceDefaultRule37.xml
  Resources/ServerInfo/DeadSpace/Guidebook/ServerRules/DeadSpaceDefaultRule38.xml
  Resources/ServerInfo/DeadSpace/Guidebook/ServerRules/DeadSpaceDefaultRule39.xml
  Resources/ServerInfo/DeadSpace/Guidebook/ServerRules/DeadSpaceDefaultRule4.xml
Labels: Status: Needs Review

#30 Фикс доминатора Dragon_fox
  Resources/Prototypes/DeadSpace/Sponsor/dragon_fox.yml
Labels: Status: Needs Review

#32 🔄 synced file(s) with dead-space-server/space-station-14
  Resources/Locale/ru-RU/objectives/conditions/kill-agent
  Resources/Locale/ru-RU/ss14-ru/prototypes/objectives/traitor.ftl
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/DeadSpace/Entities/Clothing/Uniforms/pencil_jumpskirts.yml
  Resources/Prototypes/DeadSpace/Entities/Objects/Weapons/Guns/Battery/x01.yml
  Resources/Prototypes/DeadSpace/Sith/sith.yml
  Resources/Prototypes/Entities/Objects/Shields/shields.yml
  Resources/Prototypes/Entities/Objects/Specific/syndicate.yml
  Resources/Prototypes/Objectives/traitor.yml
  Resources/Prototypes/Recipes/Construction/weapons.yml
  Resources/Prototypes/Tiles/tile_migrations.yml
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/base.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/equipped-BELT.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/icon.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/inhand-left-0.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/inhand-left-1.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/inhand-left-2.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/inhand-left-3.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/inhand-right-0.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/inhand-right-1.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/inhand-right-2.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/inhand-right-3.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/inhand-right.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-0-0.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-0-1.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-0-2.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-0.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-1-0.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-1-1.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-1-2.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-1.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-2-0.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-2-1.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-2-2.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-2.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-3-0.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-3-1.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-3-2.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-3.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-4-0.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-4-1.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-4-2.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded-4.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/mag-unshaded.png
  Resources/Textures/DeadSpace/Objects/Weapons/Guns/Battery/x01.rsi/meta.json
  Resources/Textures/Objects/Weapons/Melee/shields.rsi/meta.json
  Resources/migration.yml
Labels: Sync

#35 Фикс мантии гсб
  Resources/Prototypes/Loadouts/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
Labels: Status: Approved

#33 Новый арт в лобби для союза
  Resources/Prototypes/DeadSpace/lobbyscreens.yml
  Resources/Textures/LobbyScreens/Soyuz/attributions.yml
  Resources/Textures/LobbyScreens/Soyuz/communist_banquet.png
  Resources/Textures/LobbyScreens/Soyuz/communist_banquet.png.yml
Labels: Status: Approved

#38 Фикс скафандров карго
  Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Textures/Clothing/Head/Hardsuits/salvage.rsi/equipped-OUTERCLOTHING-vox.png
  Resources/Textures/Clothing/Head/Hardsuits/salvage.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/Head/Hardsuits/salvage.rsi/inhand-left.png
  Resources/Textures/Clothing/Head/Hardsuits/salvage.rsi/inhand-right.png
  Resources/Textures/Clothing/Head/Hardsuits/salvage.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/seniorsalvage.rsi/icon-flash.png
  Resources/Textures/Clothing/Head/Hardsuits/seniorsalvage.rsi/icon.png
  Resources/Textures/Clothing/Head/Hardsuits/seniorsalvage.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/seniorsalvage.rsi/off-equipped-HELMET-vox.png
  Resources/Textures/Clothing/Head/Hardsuits/seniorsalvage.rsi/off-equipped-HELMET.png
  Resources/Textures/Clothing/Head/Hardsuits/seniorsalvage.rsi/on-equipped-HELMET-vox.png
  Resources/Textures/Clothing/Head/Hardsuits/seniorsalvage.rsi/on-equipped-HELMET.png
Labels: Status: Needs Review

#34 КПК Тайпана
  Resources/Prototypes/DeadSpace/Entities/Objects/Devices/typan_pda.yml
  Resources/Prototypes/DeadSpace/Roles/Jobs/Typan/atmospheric_technician.yml
  Resources/Prototypes/DeadSpace/Roles/Jobs/Typan/botanist.yml
  Resources/Prototypes/DeadSpace/Roles/Jobs/Typan/cargo_technician.yml
  Resources/Prototypes/DeadSpace/Roles/Jobs/Typan/chef.yml
  Resources/Prototypes/DeadSpace/Roles/Jobs/Typan/medical_doctor.yml
  Resources/Prototypes/DeadSpace/Roles/Jobs/Typan/research_director.yml
  Resources/Prototypes/DeadSpace/Roles/Jobs/Typan/scientist.yml
  Resources/Prototypes/DeadSpace/Roles/Jobs/Typan/security_officer.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/handheld_crew_monitor.yml
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/equipped-BELT.png
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/equipped-IDCARD.png
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/id_overlay.png
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/inhand-left.png
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/insert_overlay.png
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/light_overlay.png
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/meta.json
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/pda-syndi-botan.png
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/pda-syndi-cargo.png
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/pda-syndi-chef.png
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/pda-syndi-com.png
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/pda-syndi-eng.png
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/pda-syndi-med.png
  Resources/Textures/DeadSpace/Objects/Devices/typan_pda.rsi/pda-syndi-science.png
Labels: Status: Needs Review
